# Generated by Django 4.0.3 on 2022-04-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountIngredientForRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, verbose_name='Количество ингредиента')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amountingredientforrecipe', to='recipes.ingredient', verbose_name='ID ингредиента')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amountingredientforrecipe', to='recipes.recipe', verbose_name='ID рецепта')),
            ],
            options={
                'verbose_name': 'Количество ингредиента для рецепта',
                'verbose_name_plural': 'Количество ингредиента для рецепта',
                'ordering': ['id'],
            },
        ),
    ]
