# Generated by Django 4.0.3 on 2022-04-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_amountingredientforrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredientforrecipe',
            old_name='value',
            new_name='amount',
        ),
    ]
