# Generated by Django 4.0.3 on 2022-04-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_amountingredientforrecipe_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ForeignKey', to='recipes.recipe', verbose_name='ID рецепта'),
            preserve_default=False,
        ),
    ]
