# Generated by Django 4.0.3 on 2022-04-18 16:38

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_favorite_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.hex_validator], verbose_name='Цвет в HEX'),
        ),
    ]
