# Generated by Django 4.0.3 on 2022-04-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_amountingredientforrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredientforrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amountingredientforrecipes', to='recipes.ingredient', verbose_name='ID ингредиента'),
        ),
        migrations.AlterField(
            model_name='amountingredientforrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amountingredientforrecipes', to='recipes.recipe', verbose_name='ID рецепта'),
        ),
    ]
