# Generated by Django 4.0.3 on 2022-04-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_subscription_subscription_unique_follow_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
